### ISSUE TITLE
exporting/importing takes longer the mysqldump

### ISSUE THREAD

**Issue by ghost** [gocom/danpu#19]
exporting and importing a database takes longer than CLI mysqldump. Is there a way to speed this up?

Nothing immediate jumps out in Config.php

specifics: mysqldump created a file of 840M and took approximately 1 minute

this library took just over 15 minutes and created a file size of 930 M

**Comment by vojtabiberle** [comment]
It depends on how mysqldump create inserts. Mysqldump uses multiple rows in one insert command. This is nice for export and size of dump files, but size of one insert depends on setting of mysql server. When you have same setting (net_buffer_length) all work fine, but when source server have bigger value than destination server, insert fails.

Is more secure to make single insert at one row.

You can emulate same behavior with myslqdump --skip-extended-insert option.
