### ISSUE TITLE
read and write permission

### ISSUE THREAD

**Issue by nowfalsalahudeen** [gocom/danpu#22]
i cannot read the exported sql file bcoz its read and write protected why

**Comment by gocom** [comment]
Sounds like the user that you are trying to open the file as does not have read access to the file, which is pretty much what you said, but it would be the reason. You are likely running the PHP process under an user whose files you don't have read access to, or etc.

You could either change the user that PHP ran under (or change the way your permissions are set up), chown/chmod the created file to grant read access to it or try to read it as a different user.
